# Nome da aplicação (só informativo)
spring.application.name=Sistema-de-Gestao-de-Estoque-e-Caixa

# ========================
# CONFIGURAÇÃO DO BANCO H2
# ========================

# URL do banco H2 ? "mem" indica que é em memória
spring.datasource.url=jdbc:h2:mem:sistema_estoque_caixa

# Usuário e senha do banco (padrão)
spring.datasource.username=teste
spring.datasource.password=123

# Driver JDBC do H2
spring.datasource.driver-class-name=org.h2.Driver

# Mostrar SQL gerado no console
spring.jpa.show-sql=true

# Formatar SQL (deixa legível)
spring.jpa.properties.hibernate.format_sql=true

# Criar/atualizar automaticamente o esquema (útil para dev)
spring.jpa.hibernate.ddl-auto=update
# (use 'create-drop' se quiser que ele limpe e recrie o banco a cada execução)

# Dialeto específico do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ========================
# CONSOLE WEB DO H2
# ========================
# Ativa o console web para você visualizar o banco pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
